name: Build on push to branch

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: read  # This is required to handle authentication to our artifact publishing API

jobs:
  build-daily:
    uses: ./.github/workflows/debos.yml
