name: Daily Build

on:
  # run daily at 8:30am
  schedule:
    - cron: '30 8 * * *'
  # allow manual runs
  workflow_dispatch:

permissions:
  contents: read
  security-events: read  # This is required to handle authentication to our artifact publishing API

jobs:
  build-daily:
    uses: ./.github/workflows/debos.yml
