name: Build on PR

on:
  pull_request:

permissions:
  contents: read
  security-events: read  # This is required to handle authentication to our artifact publishing API

jobs:
  build-pr:
    uses: ./.github/workflows/debos.yml

